id = "id"
usr = "username"
txt = "text"
date = "date"
rtw = "retweets"
fav = "favorites"
tag = "tag"
ner = "ner"
tags = "hashtags"
count = "count"
sum = "sum"
token = "token"
senti = "sentiment"
ratio = "ratio"
positive = "positive"

t_ratio = "t_ratio"
h_ratio = "h_ratio"
winner = "winner"

sum_count = "sum(count)"
sum_value = "sum(value)"

hillary = "hillary"
trump = "trump"

name = "name"
value = "value"
